from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class HomeWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Home Page")
        Form.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 1))
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: #B6D0E2;")
        self.mainWidget = QtWidgets.QWidget(Form)
        self.mainWidget.setObjectName("mainWidget")
        self.background = QtWidgets.QWidget(self.mainWidget)
        self.background.setGeometry(QtCore.QRect(150, 0, 1771, 1061))
        self.background.setStyleSheet("background-color: #F8F8F8;\n"
"border-bottom-left-radius: 30px;\n"
"border-top-left-radius: 30px;")
        self.background.setObjectName("background")
        self.num_appt_frame = QtWidgets.QFrame(self.background)
        self.num_appt_frame.setGeometry(QtCore.QRect(50, 140, 1000, 230))
        self.num_appt_frame.setStyleSheet("border-radius: 10px;\n"
"    background-color: #B6D0E2;\n"
"    background-image: qlineargradient(\n"
"        spread: pad, \n"
"        x1: 0, y1: 0, \n"
"        x2: 0, y2: 1, \n"
"        stop: 0 #B6D0E2, \n"
"        stop: 1 #FFFFFF\n"
"    );")
        self.num_appt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.num_appt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.num_appt_frame.setObjectName("num_appt_frame")
        self.num_upcoming_appt_label = QtWidgets.QLabel(self.num_appt_frame)
        self.num_upcoming_appt_label.setGeometry(QtCore.QRect(20, 20, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(22)
        self.num_upcoming_appt_label.setFont(font)
        self.num_upcoming_appt_label.setWordWrap(True)
        self.num_upcoming_appt_label.setObjectName("num_upcoming_appt_label")
        self.num_appt_number_label = QtWidgets.QLabel(self.num_appt_frame)
        self.num_appt_number_label.setGeometry(QtCore.QRect(30, 100, 51, 71))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(48)
        self.num_appt_number_label.setFont(font)
        self.num_appt_number_label.setObjectName("num_appt_number_label")
        self.appointment_frame = QtWidgets.QFrame(self.background)
        self.appointment_frame.setGeometry(QtCore.QRect(50, 410, 1000, 600))
        self.appointment_frame.setStyleSheet("border: 2px solid #F8F8F8;\n"
"border-radius: 10px;\n"
"\n"
"")
        self.appointment_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appointment_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appointment_frame.setLineWidth(6)
        self.appointment_frame.setObjectName("appointment_frame")
        self.upcomin_appt_frame = QtWidgets.QFrame(self.appointment_frame)
        self.upcomin_appt_frame.setGeometry(QtCore.QRect(30, 30, 450, 531))
        self.upcomin_appt_frame.setStyleSheet("background-color : #ffffff;")
        self.upcomin_appt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upcomin_appt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upcomin_appt_frame.setObjectName("upcomin_appt_frame")
        self.upcoming_label = QtWidgets.QLabel(self.upcomin_appt_frame)
        self.upcoming_label.setGeometry(QtCore.QRect(30, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.upcoming_label.setFont(font)
        self.upcoming_label.setStyleSheet("border : none;\n"
"")
        self.upcoming_label.setObjectName("upcoming_label")
        self.clinicAppt_frame = QtWidgets.QFrame(self.upcomin_appt_frame)
        self.clinicAppt_frame.setGeometry(QtCore.QRect(20, 70, 401, 81))
        self.clinicAppt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame.setObjectName("clinicAppt_frame")
        self.clinic_name_label = QtWidgets.QLabel(self.clinicAppt_frame)
        self.clinic_name_label.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label.setFont(font)
        self.clinic_name_label.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label.setObjectName("clinic_name_label")
        self.clinic_logo_label = QtWidgets.QLabel(self.clinicAppt_frame)
        self.clinic_logo_label.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label.setFont(font)
        self.clinic_logo_label.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label.setObjectName("clinic_logo_label")
        self.toa_label = QtWidgets.QLabel(self.clinicAppt_frame)
        self.toa_label.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label.setFont(font)
        self.toa_label.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label.setObjectName("toa_label")
        self.date_time_frame = QtWidgets.QFrame(self.clinicAppt_frame)
        self.date_time_frame.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame.setObjectName("date_time_frame")
        self.date_label = QtWidgets.QLabel(self.date_time_frame)
        self.date_label.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("border : none;\n"
"")
        self.date_label.setObjectName("date_label")
        self.time_label = QtWidgets.QLabel(self.date_time_frame)
        self.time_label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("border : none;\n"
"")
        self.time_label.setObjectName("time_label")
        self.clinicAppt_frame_2 = QtWidgets.QFrame(self.upcomin_appt_frame)
        self.clinicAppt_frame_2.setGeometry(QtCore.QRect(20, 170, 401, 81))
        self.clinicAppt_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame_2.setObjectName("clinicAppt_frame_2")
        self.clinic_name_label_2 = QtWidgets.QLabel(self.clinicAppt_frame_2)
        self.clinic_name_label_2.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label_2.setFont(font)
        self.clinic_name_label_2.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label_2.setObjectName("clinic_name_label_2")
        self.clinic_logo_label_2 = QtWidgets.QLabel(self.clinicAppt_frame_2)
        self.clinic_logo_label_2.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label_2.setFont(font)
        self.clinic_logo_label_2.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label_2.setObjectName("clinic_logo_label_2")
        self.toa_label_2 = QtWidgets.QLabel(self.clinicAppt_frame_2)
        self.toa_label_2.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label_2.setFont(font)
        self.toa_label_2.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label_2.setObjectName("toa_label_2")
        self.date_time_frame_2 = QtWidgets.QFrame(self.clinicAppt_frame_2)
        self.date_time_frame_2.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame_2.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame_2.setObjectName("date_time_frame_2")
        self.date_label_2 = QtWidgets.QLabel(self.date_time_frame_2)
        self.date_label_2.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label_2.setFont(font)
        self.date_label_2.setStyleSheet("border : none;\n"
"")
        self.date_label_2.setObjectName("date_label_2")
        self.time_label_2 = QtWidgets.QLabel(self.date_time_frame_2)
        self.time_label_2.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label_2.setFont(font)
        self.time_label_2.setStyleSheet("border : none;\n"
"")
        self.time_label_2.setObjectName("time_label_2")
        self.clinicAppt_frame_3 = QtWidgets.QFrame(self.upcomin_appt_frame)
        self.clinicAppt_frame_3.setGeometry(QtCore.QRect(20, 270, 401, 81))
        self.clinicAppt_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame_3.setObjectName("clinicAppt_frame_3")
        self.clinic_name_label_3 = QtWidgets.QLabel(self.clinicAppt_frame_3)
        self.clinic_name_label_3.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label_3.setFont(font)
        self.clinic_name_label_3.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label_3.setObjectName("clinic_name_label_3")
        self.clinic_logo_label_3 = QtWidgets.QLabel(self.clinicAppt_frame_3)
        self.clinic_logo_label_3.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label_3.setFont(font)
        self.clinic_logo_label_3.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label_3.setObjectName("clinic_logo_label_3")
        self.toa_label_3 = QtWidgets.QLabel(self.clinicAppt_frame_3)
        self.toa_label_3.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label_3.setFont(font)
        self.toa_label_3.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label_3.setObjectName("toa_label_3")
        self.date_time_frame_3 = QtWidgets.QFrame(self.clinicAppt_frame_3)
        self.date_time_frame_3.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame_3.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame_3.setObjectName("date_time_frame_3")
        self.date_label_3 = QtWidgets.QLabel(self.date_time_frame_3)
        self.date_label_3.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label_3.setFont(font)
        self.date_label_3.setStyleSheet("border : none;\n"
"")
        self.date_label_3.setObjectName("date_label_3")
        self.time_label_3 = QtWidgets.QLabel(self.date_time_frame_3)
        self.time_label_3.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label_3.setFont(font)
        self.time_label_3.setStyleSheet("border : none;\n"
"")
        self.time_label_3.setObjectName("time_label_3")
        self.upcomin_appt_frame_2 = QtWidgets.QFrame(self.appointment_frame)
        self.upcomin_appt_frame_2.setGeometry(QtCore.QRect(510, 30, 450, 531))
        self.upcomin_appt_frame_2.setStyleSheet("background-color : #ffffff;")
        self.upcomin_appt_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upcomin_appt_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upcomin_appt_frame_2.setObjectName("upcomin_appt_frame_2")
        self.upcoming_label_2 = QtWidgets.QLabel(self.upcomin_appt_frame_2)
        self.upcoming_label_2.setGeometry(QtCore.QRect(30, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.upcoming_label_2.setFont(font)
        self.upcoming_label_2.setStyleSheet("border : none;\n"
"")
        self.upcoming_label_2.setObjectName("upcoming_label_2")
        self.clinicAppt_frame_4 = QtWidgets.QFrame(self.upcomin_appt_frame_2)
        self.clinicAppt_frame_4.setGeometry(QtCore.QRect(20, 170, 401, 81))
        self.clinicAppt_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame_4.setObjectName("clinicAppt_frame_4")
        self.clinic_name_label_4 = QtWidgets.QLabel(self.clinicAppt_frame_4)
        self.clinic_name_label_4.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label_4.setFont(font)
        self.clinic_name_label_4.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label_4.setObjectName("clinic_name_label_4")
        self.clinic_logo_label_4 = QtWidgets.QLabel(self.clinicAppt_frame_4)
        self.clinic_logo_label_4.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label_4.setFont(font)
        self.clinic_logo_label_4.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label_4.setObjectName("clinic_logo_label_4")
        self.toa_label_4 = QtWidgets.QLabel(self.clinicAppt_frame_4)
        self.toa_label_4.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label_4.setFont(font)
        self.toa_label_4.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label_4.setObjectName("toa_label_4")
        self.date_time_frame_4 = QtWidgets.QFrame(self.clinicAppt_frame_4)
        self.date_time_frame_4.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame_4.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame_4.setObjectName("date_time_frame_4")
        self.date_label_4 = QtWidgets.QLabel(self.date_time_frame_4)
        self.date_label_4.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label_4.setFont(font)
        self.date_label_4.setStyleSheet("border : none;\n"
"")
        self.date_label_4.setObjectName("date_label_4")
        self.time_label_4 = QtWidgets.QLabel(self.date_time_frame_4)
        self.time_label_4.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label_4.setFont(font)
        self.time_label_4.setStyleSheet("border : none;\n"
"")
        self.time_label_4.setObjectName("time_label_4")
        self.clinicAppt_frame_5 = QtWidgets.QFrame(self.upcomin_appt_frame_2)
        self.clinicAppt_frame_5.setGeometry(QtCore.QRect(20, 270, 401, 81))
        self.clinicAppt_frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame_5.setObjectName("clinicAppt_frame_5")
        self.clinic_name_label_5 = QtWidgets.QLabel(self.clinicAppt_frame_5)
        self.clinic_name_label_5.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label_5.setFont(font)
        self.clinic_name_label_5.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label_5.setObjectName("clinic_name_label_5")
        self.clinic_logo_label_5 = QtWidgets.QLabel(self.clinicAppt_frame_5)
        self.clinic_logo_label_5.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label_5.setFont(font)
        self.clinic_logo_label_5.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label_5.setObjectName("clinic_logo_label_5")
        self.toa_label_5 = QtWidgets.QLabel(self.clinicAppt_frame_5)
        self.toa_label_5.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label_5.setFont(font)
        self.toa_label_5.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label_5.setObjectName("toa_label_5")
        self.date_time_frame_5 = QtWidgets.QFrame(self.clinicAppt_frame_5)
        self.date_time_frame_5.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame_5.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame_5.setObjectName("date_time_frame_5")
        self.date_label_5 = QtWidgets.QLabel(self.date_time_frame_5)
        self.date_label_5.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label_5.setFont(font)
        self.date_label_5.setStyleSheet("border : none;\n"
"")
        self.date_label_5.setObjectName("date_label_5")
        self.time_label_5 = QtWidgets.QLabel(self.date_time_frame_5)
        self.time_label_5.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label_5.setFont(font)
        self.time_label_5.setStyleSheet("border : none;\n"
"")
        self.time_label_5.setObjectName("time_label_5")
        self.clinicAppt_frame_6 = QtWidgets.QFrame(self.upcomin_appt_frame_2)
        self.clinicAppt_frame_6.setGeometry(QtCore.QRect(20, 70, 401, 81))
        self.clinicAppt_frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clinicAppt_frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clinicAppt_frame_6.setObjectName("clinicAppt_frame_6")
        self.clinic_name_label_6 = QtWidgets.QLabel(self.clinicAppt_frame_6)
        self.clinic_name_label_6.setGeometry(QtCore.QRect(90, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.clinic_name_label_6.setFont(font)
        self.clinic_name_label_6.setStyleSheet("border : none;\n"
"")
        self.clinic_name_label_6.setObjectName("clinic_name_label_6")
        self.clinic_logo_label_6 = QtWidgets.QLabel(self.clinicAppt_frame_6)
        self.clinic_logo_label_6.setGeometry(QtCore.QRect(10, 10, 54, 54))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(9)
        self.clinic_logo_label_6.setFont(font)
        self.clinic_logo_label_6.setStyleSheet("background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.clinic_logo_label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.clinic_logo_label_6.setObjectName("clinic_logo_label_6")
        self.toa_label_6 = QtWidgets.QLabel(self.clinicAppt_frame_6)
        self.toa_label_6.setGeometry(QtCore.QRect(90, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.toa_label_6.setFont(font)
        self.toa_label_6.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.toa_label_6.setObjectName("toa_label_6")
        self.date_time_frame_6 = QtWidgets.QFrame(self.clinicAppt_frame_6)
        self.date_time_frame_6.setGeometry(QtCore.QRect(280, 20, 71, 41))
        self.date_time_frame_6.setStyleSheet("border-radius: 10px;\n"
"background-color: #dbe7f0;")
        self.date_time_frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.date_time_frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_time_frame_6.setObjectName("date_time_frame_6")
        self.date_label_6 = QtWidgets.QLabel(self.date_time_frame_6)
        self.date_label_6.setGeometry(QtCore.QRect(10, 0, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.date_label_6.setFont(font)
        self.date_label_6.setStyleSheet("border : none;\n"
"")
        self.date_label_6.setObjectName("date_label_6")
        self.time_label_6 = QtWidgets.QLabel(self.date_time_frame_6)
        self.time_label_6.setGeometry(QtCore.QRect(10, 20, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        self.time_label_6.setFont(font)
        self.time_label_6.setStyleSheet("border : none;\n"
"")
        self.time_label_6.setObjectName("time_label_6")
        self.active_pres_frame = QtWidgets.QFrame(self.background)
        self.active_pres_frame.setGeometry(QtCore.QRect(1120, 170, 481, 831))
        self.active_pres_frame.setStyleSheet("border: 2px solid #FFFFFF;\n"
"border-radius: 10px;")
        self.active_pres_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.active_pres_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.active_pres_frame.setObjectName("active_pres_frame")
        self.active_pres_label = QtWidgets.QLabel(self.active_pres_frame)
        self.active_pres_label.setGeometry(QtCore.QRect(20, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.active_pres_label.setFont(font)
        self.active_pres_label.setStyleSheet("border : none;\n"
"")
        self.active_pres_label.setObjectName("active_pres_label")
        self.active_pres1_frame = QtWidgets.QFrame(self.active_pres_frame)
        self.active_pres1_frame.setGeometry(QtCore.QRect(0, 50, 481, 71))
        self.active_pres1_frame.setStyleSheet("border : none;\n"
"border-radius : 0;\n"
"background-color : #FFFFFF;")
        self.active_pres1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.active_pres1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.active_pres1_frame.setObjectName("active_pres1_frame")
        self.medicineName_label = QtWidgets.QLabel(self.active_pres1_frame)
        self.medicineName_label.setGeometry(QtCore.QRect(60, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.medicineName_label.setFont(font)
        self.medicineName_label.setObjectName("medicineName_label")
        self.medicine_quantity_label = QtWidgets.QLabel(self.active_pres1_frame)
        self.medicine_quantity_label.setGeometry(QtCore.QRect(60, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.medicine_quantity_label.setFont(font)
        self.medicine_quantity_label.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.medicine_quantity_label.setObjectName("medicine_quantity_label")
        self.active_pres1_frame_2 = QtWidgets.QFrame(self.active_pres_frame)
        self.active_pres1_frame_2.setGeometry(QtCore.QRect(0, 140, 481, 71))
        self.active_pres1_frame_2.setStyleSheet("border : none;\n"
"border-radius : 0;\n"
"background-color : #FFFFFF;")
        self.active_pres1_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.active_pres1_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.active_pres1_frame_2.setObjectName("active_pres1_frame_2")
        self.medicineName_label_2 = QtWidgets.QLabel(self.active_pres1_frame_2)
        self.medicineName_label_2.setGeometry(QtCore.QRect(60, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.medicineName_label_2.setFont(font)
        self.medicineName_label_2.setObjectName("medicineName_label_2")
        self.medicine_quantity_label_2 = QtWidgets.QLabel(self.active_pres1_frame_2)
        self.medicine_quantity_label_2.setGeometry(QtCore.QRect(60, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.medicine_quantity_label_2.setFont(font)
        self.medicine_quantity_label_2.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.medicine_quantity_label_2.setObjectName("medicine_quantity_label_2")
        self.active_pres1_frame_3 = QtWidgets.QFrame(self.active_pres_frame)
        self.active_pres1_frame_3.setGeometry(QtCore.QRect(0, 230, 481, 71))
        self.active_pres1_frame_3.setStyleSheet("border : none;\n"
"border-radius : 0;\n"
"background-color : #FFFFFF;")
        self.active_pres1_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.active_pres1_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.active_pres1_frame_3.setObjectName("active_pres1_frame_3")
        self.medicineName_label_3 = QtWidgets.QLabel(self.active_pres1_frame_3)
        self.medicineName_label_3.setGeometry(QtCore.QRect(60, 10, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        self.medicineName_label_3.setFont(font)
        self.medicineName_label_3.setObjectName("medicineName_label_3")
        self.medicine_quantity_label_3 = QtWidgets.QLabel(self.active_pres1_frame_3)
        self.medicine_quantity_label_3.setGeometry(QtCore.QRect(60, 30, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(10)
        self.medicine_quantity_label_3.setFont(font)
        self.medicine_quantity_label_3.setStyleSheet("border : none;\n"
"color : #6ea0c4;\n"
"")
        self.medicine_quantity_label_3.setObjectName("medicine_quantity_label_3")
        self.noti_icon = QtWidgets.QPushButton(self.background)
        self.noti_icon.setGeometry(QtCore.QRect(1380, 30, 70, 81))
        self.noti_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CAD/Images/icon/notification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noti_icon.setIcon(icon)
        self.noti_icon.setIconSize(QtCore.QSize(40, 40))
        self.noti_icon.setObjectName("noti_icon")
        self.user_frame = QtWidgets.QFrame(self.background)
        self.user_frame.setGeometry(QtCore.QRect(1480, 30, 251, 80))
        self.user_frame.setStyleSheet("border-radius: 20px; border: 2px solid #808080")
        self.user_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_frame.setObjectName("user_frame")
        self.profile_icon = QtWidgets.QLabel(self.user_frame)
        self.profile_icon.setGeometry(QtCore.QRect(10, 10, 60, 60))
        self.profile_icon.setStyleSheet("border: none")
        self.profile_icon.setText("")
        self.profile_icon.setPixmap(QtGui.QPixmap("CAD/Images/icon/profile_icon.png"))
        self.profile_icon.setScaledContents(True)
        self.profile_icon.setObjectName("profile_icon")
        self.profile_btn = QtWidgets.QPushButton(self.user_frame)
        self.profile_btn.setGeometry(QtCore.QRect(120, 25, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.profile_btn.setFont(font)
        self.profile_btn.setStyleSheet("border: none")
        self.profile_btn.setObjectName("profile_btn")
        self.frame = QtWidgets.QFrame(self.mainWidget)
        self.frame.setGeometry(QtCore.QRect(10, 90, 111, 901))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.home_navigation = QtWidgets.QToolButton(self.frame)
        self.home_navigation.setEnabled(True)
        self.home_navigation.setGeometry(QtCore.QRect(20, 80, 73, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_navigation.sizePolicy().hasHeightForWidth())
        self.home_navigation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.home_navigation.setFont(font)
        self.home_navigation.setStyleSheet("border: none; \n"
"color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("CAD/Images/nav_images/home_page_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_navigation.setIcon(icon1)
        self.home_navigation.setIconSize(QtCore.QSize(70, 70))
        self.home_navigation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.home_navigation.setObjectName("home_navigation")
        self.appointments_navigation = QtWidgets.QToolButton(self.frame)
        self.appointments_navigation.setEnabled(True)
        self.appointments_navigation.setGeometry(QtCore.QRect(10, 250, 88, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appointments_navigation.sizePolicy().hasHeightForWidth())
        self.appointments_navigation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.appointments_navigation.setFont(font)
        self.appointments_navigation.setStyleSheet("border: none; \n"
"color: white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("CAD/Images/nav_images/appointment_page_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointments_navigation.setIcon(icon2)
        self.appointments_navigation.setIconSize(QtCore.QSize(70, 70))
        self.appointments_navigation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.appointments_navigation.setObjectName("appointments_navigation")
        self.services_navigation = QtWidgets.QToolButton(self.frame)
        self.services_navigation.setEnabled(True)
        self.services_navigation.setGeometry(QtCore.QRect(20, 430, 73, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.services_navigation.sizePolicy().hasHeightForWidth())
        self.services_navigation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.services_navigation.setFont(font)
        self.services_navigation.setStyleSheet("border: none; \n"
"color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("CAD/Images/nav_images/services_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.services_navigation.setIcon(icon3)
        self.services_navigation.setIconSize(QtCore.QSize(70, 70))
        self.services_navigation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.services_navigation.setObjectName("services_navigation")
        self.settings_navigation = QtWidgets.QToolButton(self.frame)
        self.settings_navigation.setEnabled(True)
        self.settings_navigation.setGeometry(QtCore.QRect(20, 580, 73, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_navigation.sizePolicy().hasHeightForWidth())
        self.settings_navigation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.settings_navigation.setFont(font)
        self.settings_navigation.setStyleSheet("border: none; \n"
"color: white;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("CAD/Images/nav_images/settings_page_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_navigation.setIcon(icon4)
        self.settings_navigation.setIconSize(QtCore.QSize(70, 70))
        self.settings_navigation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settings_navigation.setObjectName("settings_navigation")
        self.logout_navigation = QtWidgets.QToolButton(self.frame)
        self.logout_navigation.setEnabled(True)
        self.logout_navigation.setGeometry(QtCore.QRect(20, 770, 73, 94))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_navigation.sizePolicy().hasHeightForWidth())
        self.logout_navigation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Source Sans Pro Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logout_navigation.setFont(font)
        self.logout_navigation.setStyleSheet("border: none; \n"
"color: white;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("CAD/Images/nav_images/logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_navigation.setIcon(icon5)
        self.logout_navigation.setIconSize(QtCore.QSize(70, 70))
        self.logout_navigation.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.logout_navigation.setObjectName("logout_navigation")
        # Form.setCentralWidget(self.mainWidget)
        # self.menubar = QtWidgets.QMenuBar(Form)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        # self.menubar.setObjectName("menubar")
        # Form.setMenuBar(self.menubar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Call A Doctor"))
        self.num_upcoming_appt_label.setText(_translate("MainWindow", "Number of upcoming appointments :"))
        self.num_appt_number_label.setText(_translate("MainWindow", "2"))
        self.upcoming_label.setText(_translate("MainWindow", "Upcoming"))
        self.clinic_name_label.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label.setText(_translate("MainWindow", "A"))
        self.toa_label.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.clinic_name_label_2.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label_2.setText(_translate("MainWindow", "A"))
        self.toa_label_2.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label_2.setText(_translate("MainWindow", "Date"))
        self.time_label_2.setText(_translate("MainWindow", "Time"))
        self.clinic_name_label_3.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label_3.setText(_translate("MainWindow", "A"))
        self.toa_label_3.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label_3.setText(_translate("MainWindow", "Date"))
        self.time_label_3.setText(_translate("MainWindow", "Time"))
        self.upcoming_label_2.setText(_translate("MainWindow", "Past"))
        self.clinic_name_label_4.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label_4.setText(_translate("MainWindow", "A"))
        self.toa_label_4.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label_4.setText(_translate("MainWindow", "Date"))
        self.time_label_4.setText(_translate("MainWindow", "Time"))
        self.clinic_name_label_5.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label_5.setText(_translate("MainWindow", "A"))
        self.toa_label_5.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label_5.setText(_translate("MainWindow", "Date"))
        self.time_label_5.setText(_translate("MainWindow", "Time"))
        self.clinic_name_label_6.setText(_translate("MainWindow", "Clinic Name"))
        self.clinic_logo_label_6.setText(_translate("MainWindow", "A"))
        self.toa_label_6.setText(_translate("MainWindow", "Type of Appointment"))
        self.date_label_6.setText(_translate("MainWindow", "Date"))
        self.time_label_6.setText(_translate("MainWindow", "Time"))
        self.active_pres_label.setText(_translate("MainWindow", "Active Prescriptions"))
        self.medicineName_label.setText(_translate("MainWindow", "Medicine Name"))
        self.medicine_quantity_label.setText(_translate("MainWindow", "Quantity"))
        self.medicineName_label_2.setText(_translate("MainWindow", "Medicine Name"))
        self.medicine_quantity_label_2.setText(_translate("MainWindow", "Quantity"))
        self.medicineName_label_3.setText(_translate("MainWindow", "Medicine Name"))
        self.medicine_quantity_label_3.setText(_translate("MainWindow", "Quantity"))
        self.profile_btn.setText(_translate("MainWindow", "User"))
        self.home_navigation.setText(_translate("MainWindow", "Home"))
        self.appointments_navigation.setText(_translate("MainWindow", "Appointments"))
        self.services_navigation.setText(_translate("MainWindow", "Services"))
        self.settings_navigation.setText(_translate("MainWindow", "Settings"))
        self.logout_navigation.setText(_translate("MainWindow", "Logout"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = HomeWidget()
#     ui.setupUi(MainWindow)
#     MainWindow.showMaximized()
#     sys.exit(app.exec_())
