from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt, pyqtSignal, pyqtSlot)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class ViewClinicProfileWidget(QWidget):
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1920, 1080)
        
        Form.setAutoFillBackground(True)
        p = Form.palette()
        p.setColor(Form.backgroundRole(), QColor('#B6D0E2'))
        Form.setPalette(p)
        
        self.whitebg = QWidget(Form)
        self.whitebg.setObjectName(u"whitebg")
        self.whitebg.setGeometry(QRect(150, 0, 1771, 1080))
        self.whitebg.setCursor(QCursor(Qt.ArrowCursor))
        self.whitebg.setStyleSheet(u"background-color: #F8F8F8;\n"
"border-bottom-left-radius: 30px;\n"
"border-top-left-radius: 30px;\n"
"")
        self.noti_icon = QPushButton(self.whitebg)
        self.noti_icon.setObjectName(u"noti_icon")
        self.noti_icon.setGeometry(QRect(1380, 30, 70, 81))
        icon = QIcon()
        icon.addFile(u"CAD/Images/icon/notification.png", QSize(), QIcon.Normal, QIcon.Off)
        self.noti_icon.setIcon(icon)
        self.noti_icon.setIconSize(QSize(40, 40))
        self.fad_title = QLabel(self.whitebg)
        self.fad_title.setObjectName(u"fad_title")
        self.fad_title.setGeometry(QRect(60, 40, 481, 81))
        font = QFont()
        font.setFamily(u"Consolas")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.fad_title.setFont(font)
        self.user_frame = QFrame(self.whitebg)
        self.user_frame.setObjectName(u"user_frame")
        self.user_frame.setGeometry(QRect(1480, 30, 251, 80))
        self.user_frame.setStyleSheet(u"border-radius: 20px; border: 2px solid #808080")
        self.user_frame.setFrameShape(QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QFrame.Raised)
        self.profile_icon = QLabel(self.user_frame)
        self.profile_icon.setObjectName(u"profile_icon")
        self.profile_icon.setGeometry(QRect(10, 10, 60, 60))
        self.profile_icon.setStyleSheet(u"border: none")
        self.profile_icon.setPixmap(QPixmap(u"CAD/Images/icon/profile_icon.png"))
        self.profile_icon.setScaledContents(True)
        self.profile_btn = QPushButton(self.user_frame)
        self.profile_btn.setObjectName(u"profile_btn")
        self.profile_btn.setGeometry(QRect(120, 25, 71, 31))
        font1 = QFont()
        font1.setFamily(u"Consolas")
        font1.setPointSize(16)
        self.profile_btn.setFont(font1)
        self.profile_btn.setStyleSheet(u"border: none")
        self.profile_display_frame = QFrame(self.whitebg)
        self.profile_display_frame.setObjectName(u"profile_display_frame")
        self.profile_display_frame.setGeometry(QRect(60, 150, 1661, 880))
        self.profile_display_frame.setStyleSheet(u"background-color: white;")
        self.profile_display_frame.setFrameShape(QFrame.StyledPanel)
        self.profile_display_frame.setFrameShadow(QFrame.Raised)
        self.doc_img = QLabel(self.profile_display_frame)
        self.doc_img.setObjectName(u"doc_img")
        self.doc_img.setGeometry(QRect(130, 90, 284, 284))
        self.doc_img.setMinimumSize(QSize(284, 284))
        self.doc_img.setMaximumSize(QSize(16777215, 16777215))
        self.doc_img.setStyleSheet(u"text-align: center;  border-radius: 142px; border: 1px solid black; ")
        self.doc_img.setAlignment(Qt.AlignCenter)
        self.layoutWidget = QWidget(self.profile_display_frame)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(625, 68, 1011, 511))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.location_layout = QVBoxLayout()
        self.location_layout.setSpacing(10)
        self.location_layout.setObjectName(u"location_layout")
        self.location_label = QLabel(self.layoutWidget)
        self.location_label.setObjectName(u"location_label")
        self.location_label.setMinimumSize(QSize(0, 30))
        self.location_label.setMaximumSize(QSize(16777215, 30))
        font2 = QFont()
        font2.setFamily(u"Consolas")
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.location_label.setFont(font2)
        self.location_label.setStyleSheet(u"text-align: center; border: none;")

        self.location_layout.addWidget(self.location_label)

        self.location_display = QLabel(self.layoutWidget)
        self.location_display.setObjectName(u"location_display")
        self.location_display.setMinimumSize(QSize(1000, 80))
        self.location_display.setMaximumSize(QSize(1000, 80))
        font3 = QFont()
        font3.setFamily(u"Consolas")
        font3.setPointSize(12)
        self.location_display.setFont(font3)
        self.location_display.setStyleSheet(u"text-align: center; border: 1px solid black; border-radius: 0px;")
        self.location_display.setWordWrap(True)

        self.location_layout.addWidget(self.location_display)


        self.verticalLayout.addLayout(self.location_layout)

        self.intro_layout = QVBoxLayout()
        self.intro_layout.setSpacing(10)
        self.intro_layout.setObjectName(u"intro_layout")
        self.intro_label = QLabel(self.layoutWidget)
        self.intro_label.setObjectName(u"intro_label")
        self.intro_label.setMinimumSize(QSize(0, 30))
        self.intro_label.setMaximumSize(QSize(16777215, 30))
        self.intro_label.setFont(font2)
        self.intro_label.setStyleSheet(u"text-align: center; border: none;")

        self.intro_layout.addWidget(self.intro_label)

        self.intro_display = QLabel(self.layoutWidget)
        self.intro_display.setObjectName(u"intro_display")
        self.intro_display.setMinimumSize(QSize(1000, 80))
        self.intro_display.setMaximumSize(QSize(1000, 80))
        self.intro_display.setFont(font3)
        self.intro_display.setStyleSheet(u"text-align: center; border: 1px solid black; border-radius: 0px;")
        self.intro_display.setWordWrap(True)

        self.intro_layout.addWidget(self.intro_display)


        self.verticalLayout.addLayout(self.intro_layout)

        self.ophour_layout = QVBoxLayout()
        self.ophour_layout.setSpacing(10)
        self.ophour_layout.setObjectName(u"ophour_layout")
        self.ophour_label = QLabel(self.layoutWidget)
        self.ophour_label.setObjectName(u"ophour_label")
        self.ophour_label.setMinimumSize(QSize(0, 30))
        self.ophour_label.setMaximumSize(QSize(16777215, 30))
        self.ophour_label.setFont(font2)
        self.ophour_label.setStyleSheet(u"text-align: center; border: none;")

        self.ophour_layout.addWidget(self.ophour_label)

        self.ophour_display = QLabel(self.layoutWidget)
        self.ophour_display.setObjectName(u"ophour_display")
        self.ophour_display.setMinimumSize(QSize(1000, 80))
        self.ophour_display.setMaximumSize(QSize(1000, 80))
        self.ophour_display.setFont(font3)
        self.ophour_display.setStyleSheet(u"text-align: center; border: 1px solid black; border-radius: 0px;")
        self.ophour_display.setWordWrap(True)

        self.ophour_layout.addWidget(self.ophour_display)


        self.verticalLayout.addLayout(self.ophour_layout)

        self.doctors_available_label = QLabel(self.profile_display_frame)
        self.doctors_available_label.setObjectName(u"doctors_available_label")
        self.doctors_available_label.setGeometry(QRect(80, 640, 1491, 50))
        self.doctors_available_label.setMinimumSize(QSize(400, 50))
        self.doctors_available_label.setMaximumSize(QSize(16777215, 30))
        self.doctors_available_label.setFont(font2)
        self.doctors_available_label.setStyleSheet(u"text-align: center; border: none;")
        self.doctors_available_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.doctors_available_label.setWordWrap(True)
        self.line = QFrame(self.profile_display_frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(80, 610, 1491, 3))
        self.line.setMinimumSize(QSize(0, 3))
        self.line.setMaximumSize(QSize(16777215, 3))
        self.line.setStyleSheet(u"background-color: #B6D0E2; border: none;")
        self.line.setFrameShape(QFrame.StyledPanel)
        self.line.setFrameShadow(QFrame.Raised)
        self.clinic_name = QLabel(self.profile_display_frame)
        self.clinic_name.setObjectName(u"clinic_name")
        self.clinic_name.setGeometry(QRect(80, 430, 400, 100))
        self.clinic_name.setMinimumSize(QSize(400, 100))
        self.clinic_name.setMaximumSize(QSize(16777215, 16777215))
        self.clinic_name.setFont(font2)
        self.clinic_name.setStyleSheet(u"text-align: center; border: none;")
        self.clinic_name.setAlignment(Qt.AlignCenter)
        self.clinic_name.setWordWrap(True)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 90, 141, 891))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.layoutWidget_4 = QWidget(self.frame)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(30, 19, 87, 871))
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.home_navigation = QToolButton(self.layoutWidget_4)
        self.home_navigation.setObjectName(u"home_navigation")
        self.home_navigation.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_navigation.sizePolicy().hasHeightForWidth())
        self.home_navigation.setSizePolicy(sizePolicy)
        self.home_navigation.setMinimumSize(QSize(85, 96))
        self.home_navigation.setMaximumSize(QSize(85, 96))
        font4 = QFont()
        font4.setFamily(u"Source Sans Pro Semibold")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.home_navigation.setFont(font4)
        self.home_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon1 = QIcon()
        icon1.addFile(u"CAD/Images/nav_images/home_page_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.home_navigation.setIcon(icon1)
        self.home_navigation.setIconSize(QSize(70, 70))
        self.home_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout_2.addWidget(self.home_navigation)

        self.appointments_navigation = QToolButton(self.layoutWidget_4)
        self.appointments_navigation.setObjectName(u"appointments_navigation")
        self.appointments_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.appointments_navigation.sizePolicy().hasHeightForWidth())
        self.appointments_navigation.setSizePolicy(sizePolicy)
        self.appointments_navigation.setFont(font4)
        self.appointments_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon2 = QIcon()
        icon2.addFile(u"CAD/Images/nav_images/appointment_page_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.appointments_navigation.setIcon(icon2)
        self.appointments_navigation.setIconSize(QSize(70, 70))
        self.appointments_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout_2.addWidget(self.appointments_navigation)

        self.services_navigation = QToolButton(self.layoutWidget_4)
        self.services_navigation.setObjectName(u"services_navigation")
        self.services_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.services_navigation.sizePolicy().hasHeightForWidth())
        self.services_navigation.setSizePolicy(sizePolicy)
        self.services_navigation.setFont(font4)
        self.services_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon3 = QIcon()
        icon3.addFile(u"CAD/Images/nav_images/services_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.services_navigation.setIcon(icon3)
        self.services_navigation.setIconSize(QSize(70, 70))
        self.services_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout_2.addWidget(self.services_navigation)

        self.settings_navigation = QToolButton(self.layoutWidget_4)
        self.settings_navigation.setObjectName(u"settings_navigation")
        self.settings_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.settings_navigation.sizePolicy().hasHeightForWidth())
        self.settings_navigation.setSizePolicy(sizePolicy)
        self.settings_navigation.setFont(font4)
        self.settings_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon4 = QIcon()
        icon4.addFile(u"CAD/Images/nav_images/settings_page_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_navigation.setIcon(icon4)
        self.settings_navigation.setIconSize(QSize(70, 70))
        self.settings_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout_2.addWidget(self.settings_navigation)

        self.logout_navigation = QToolButton(self.layoutWidget_4)
        self.logout_navigation.setObjectName(u"logout_navigation")
        self.logout_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.logout_navigation.sizePolicy().hasHeightForWidth())
        self.logout_navigation.setSizePolicy(sizePolicy)
        self.logout_navigation.setFont(font4)
        self.logout_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon5 = QIcon()
        icon5.addFile(u"CAD/Images/nav_images/logout_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logout_navigation.setIcon(icon5)
        self.logout_navigation.setIconSize(QSize(70, 70))
        self.logout_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout_2.addWidget(self.logout_navigation)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.noti_icon.setText("")
        self.fad_title.setText(QCoreApplication.translate("Form", u"Clinic Profile", None))
        self.profile_icon.setText("")
        self.profile_btn.setText(QCoreApplication.translate("Form", u"User", None))
        self.doc_img.setText("")
        self.location_label.setText(QCoreApplication.translate("Form", u"Location", None))
        self.location_display.setText(QCoreApplication.translate("Form", u"sample display", None))
        self.intro_label.setText(QCoreApplication.translate("Form", u"Introduction", None))
        self.intro_display.setText(QCoreApplication.translate("Form", u"sample display", None))
        self.ophour_label.setText(QCoreApplication.translate("Form", u"Operating Hours", None))
        self.ophour_display.setText(QCoreApplication.translate("Form", u"sample display", None))
        self.doctors_available_label.setText(QCoreApplication.translate("Form", u"Doctors Available", None))
        self.clinic_name.setText(QCoreApplication.translate("Form", u"Clinic Name", None))
        self.home_navigation.setText(QCoreApplication.translate("Form", u"   Home   ", None))
        self.appointments_navigation.setText(QCoreApplication.translate("Form", u"Schedule", None))
        self.services_navigation.setText(QCoreApplication.translate("Form", u"Services", None))
        self.settings_navigation.setText(QCoreApplication.translate("Form", u"Settings", None))
        self.logout_navigation.setText(QCoreApplication.translate("Form", u"Logout", None))
    # retranslateUi

