from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt, pyqtSignal, pyqtSlot, QDate)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *
from connection import db


class CA_approved_rejectWidget(QWidget):
    home_navigation_btn_clicked = pyqtSignal()
    doctors_navigation_btn_clicked = pyqtSignal()
    patients_navigation_btn_clicked = pyqtSignal()
    logout_btn_clicked = pyqtSignal()
    profile_btn_clicked = pyqtSignal()
    settings_navigation_btn_clicked = pyqtSignal()
    approved_btn_clicked = pyqtSignal()
    reject_btn_clicked = pyqtSignal()


    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1920, 1080)
        Form.setStyleSheet(u"background-color: \"#B6D0E2\" ")
        self.background = QWidget(Form)
        self.background.setObjectName(u"background")
        self.background.setGeometry(QRect(150, 0, 1771, 1061))
        self.background.setStyleSheet(u"background-color: #F8F8F8;\n"
"border-bottom-left-radius: 30px;\n"
"border-top-left-radius: 30px;\n"
"text-align: center;")
        self.noti_icon = QPushButton(self.background)
        self.noti_icon.setObjectName(u"noti_icon")
        self.noti_icon.setGeometry(QRect(1380, 30, 70, 81))
        icon = QIcon()
        icon.addFile(u"CAD/Images/icon/notification.png", QSize(), QIcon.Normal, QIcon.Off)
        self.noti_icon.setIcon(icon)
        self.noti_icon.setIconSize(QSize(40, 40))
        self.user_frame = QFrame(self.background)
        self.user_frame.setObjectName(u"user_frame")
        self.user_frame.setGeometry(QRect(1480, 30, 251, 80))
        self.user_frame.setStyleSheet(u"border-radius: 20px; border: 2px solid #808080")
        self.user_frame.setFrameShape(QFrame.StyledPanel)
        self.user_frame.setFrameShadow(QFrame.Raised)
        self.profile_icon = QLabel(self.user_frame)
        self.profile_icon.setObjectName(u"profile_icon")
        self.profile_icon.setGeometry(QRect(10, 10, 60, 60))
        self.profile_icon.setStyleSheet(u"border: none")
        self.profile_icon.setPixmap(QPixmap(u"CAD/Images/icon/profile_icon.png"))
        self.profile_icon.setScaledContents(True)
        self.profile_btn = QPushButton(self.user_frame)
        self.profile_btn.setObjectName(u"profile_btn")
        self.profile_btn.setGeometry(QRect(100, 25, 121, 31))
        font = QFont()
        font.setFamily(u"Consolas")
        font.setPointSize(10)
        self.profile_btn.setFont(font)
        self.profile_btn.setStyleSheet(u"border: none")
        self.patient_details_outer_frame = QFrame(self.background)
        self.patient_details_outer_frame.setObjectName(u"patient_details_outer_frame")
        self.patient_details_outer_frame.setGeometry(QRect(40, 180, 751, 841))
        self.patient_details_outer_frame.setStyleSheet(u"background-color : #ffffff;")
        self.patient_details_outer_frame.setFrameShape(QFrame.StyledPanel)
        self.patient_details_outer_frame.setFrameShadow(QFrame.Raised)
        self.clinic_details_inner = QFrame(self.patient_details_outer_frame)
        self.clinic_details_inner.setObjectName(u"clinic_details_inner")
        self.clinic_details_inner.setGeometry(QRect(10, 20, 721, 751))
        self.clinic_details_inner.setFrameShape(QFrame.StyledPanel)
        self.clinic_details_inner.setFrameShadow(QFrame.Raised)
        self.patient_logo_2 = QLabel(self.clinic_details_inner)
        self.patient_logo_2.setObjectName(u"patient_logo_2")
        self.patient_logo_2.setGeometry(QRect(9, 9, 54, 54))
        font1 = QFont()
        font1.setFamily(u"Cascadia Code")
        font1.setPointSize(9)
        self.patient_logo_2.setFont(font1)
        self.patient_logo_2.setStyleSheet(u"background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.patient_logo_2.setAlignment(Qt.AlignCenter)
        self.patient_name_display = QLabel(self.clinic_details_inner)
        self.patient_name_display.setObjectName(u"patient_name_display")
        self.patient_name_display.setGeometry(QRect(9, 69, 120, 22))
        font2 = QFont()
        font2.setFamily(u"Cascadia Code")
        font2.setPointSize(10)
        self.patient_name_display.setFont(font2)
        self.patient_name_display.setStyleSheet(u"border : none;\n"
"")
        self.line_2 = QFrame(self.clinic_details_inner)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(9, 205, 703, 3))
        self.line_2.setMinimumSize(QSize(357, 3))
        self.line_2.setMaximumSize(QSize(16777215, 3))
        self.line_2.setStyleSheet(u"background-color: #B6D0E2; border: none;")
        self.line_2.setFrameShape(QFrame.StyledPanel)
        self.line_2.setFrameShadow(QFrame.Raised)
        self.diagnosis_display = QLabel(self.clinic_details_inner)
        self.diagnosis_display.setObjectName(u"diagnosis_display")
        self.diagnosis_display.setGeometry(QRect(320, 310, 390, 131))
        self.diagnosis_display.setMinimumSize(QSize(390, 0))
        font3 = QFont()
        font3.setFamily(u"Consolas")
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.diagnosis_display.setFont(font3)
        self.diagnosis_display.setStyleSheet(u"border: none;")
        self.diagnosis_display.setScaledContents(False)
        self.diagnosis_display.setWordWrap(True)
        self.diagnosis_label_2 = QLabel(self.clinic_details_inner)
        self.diagnosis_label_2.setObjectName(u"diagnosis_label_2")
        self.diagnosis_label_2.setGeometry(QRect(13, 310, 301, 131))
        font4 = QFont()
        font4.setFamily(u"Consolas")
        font4.setPointSize(11)
        font4.setBold(True)
        font4.setWeight(75)
        self.diagnosis_label_2.setFont(font4)
        self.diagnosis_label_2.setStyleSheet(u"border: none;")
        self.diagnosis_label_2.setWordWrap(True)
        self.last_checked_by_label = QLabel(self.clinic_details_inner)
        self.last_checked_by_label.setObjectName(u"last_checked_by_label")
        self.last_checked_by_label.setGeometry(QRect(13, 210, 301, 121))
        self.last_checked_by_label.setFont(font4)
        self.last_checked_by_label.setStyleSheet(u"border: none;")
        self.last_checked_by_label.setWordWrap(True)
        self.dr_name_display = QLabel(self.clinic_details_inner)
        self.dr_name_display.setObjectName(u"dr_name_display")
        self.dr_name_display.setGeometry(QRect(320, 210, 390, 121))
        self.dr_name_display.setMinimumSize(QSize(390, 0))
        self.dr_name_display.setFont(font3)
        self.dr_name_display.setStyleSheet(u"border: none;")
        self.dr_name_display.setScaledContents(False)
        self.dr_name_display.setWordWrap(True)
        self.date_label = QLabel(self.clinic_details_inner)
        self.date_label.setObjectName(u"date_label")
        self.date_label.setGeometry(QRect(13, 400, 301, 148))
        self.date_label.setFont(font4)
        self.date_label.setStyleSheet(u"border: none;")
        self.date_label.setWordWrap(True)
        self.date_display = QLabel(self.clinic_details_inner)
        self.date_display.setObjectName(u"date_display")
        self.date_display.setGeometry(QRect(320, 400, 390, 148))
        self.date_display.setMinimumSize(QSize(390, 0))
        self.date_display.setFont(font3)
        self.date_display.setStyleSheet(u"border: none;")
        self.date_display.setScaledContents(False)
        self.date_display.setWordWrap(True)
        self.time_label_3 = QLabel(self.clinic_details_inner)
        self.time_label_3.setObjectName(u"time_label_3")
        self.time_label_3.setGeometry(QRect(10, 500, 301, 148))
        self.time_label_3.setFont(font4)
        self.time_label_3.setStyleSheet(u"border: none;")
        self.time_label_3.setWordWrap(True)
        self.time_display_3 = QLabel(self.clinic_details_inner)
        self.time_display_3.setObjectName(u"time_display_3")
        self.time_display_3.setGeometry(QRect(317, 500, 390, 148))
        self.time_display_3.setMinimumSize(QSize(390, 0))
        self.time_display_3.setFont(font3)
        self.time_display_3.setStyleSheet(u"border: none;")
        self.time_display_3.setScaledContents(False)
        self.time_display_3.setWordWrap(True)
        self.doctor_name_display = QLabel(self.clinic_details_inner)
        self.doctor_name_display.setObjectName(u"doctor_name_display")
        self.doctor_name_display.setGeometry(QRect(317, 600, 390, 148))
        self.doctor_name_display.setMinimumSize(QSize(390, 0))
        self.doctor_name_display.setFont(font3)
        self.doctor_name_display.setStyleSheet(u"border: none;")
        self.doctor_name_display.setScaledContents(False)
        self.doctor_name_display.setWordWrap(True)
        self.doctor_prefered_label = QLabel(self.clinic_details_inner)
        self.doctor_prefered_label.setObjectName(u"doctor_prefered_label")
        self.doctor_prefered_label.setGeometry(QRect(10, 600, 301, 148))
        self.doctor_prefered_label.setFont(font4)
        self.doctor_prefered_label.setStyleSheet(u"border: none;")
        self.doctor_prefered_label.setWordWrap(True)
        self.reject_btn = QPushButton(self.patient_details_outer_frame)
        self.reject_btn.setObjectName(u"reject_btn")
        self.reject_btn.setGeometry(QRect(550, 780, 181, 41))
        font5 = QFont()
        font5.setFamily(u"Consolas")
        font5.setPointSize(10)
        font5.setBold(True)
        font5.setWeight(75)
        self.reject_btn.setFont(font5)
        self.reject_btn.setStyleSheet(u"background-color: #E73030; border-radius: 16px; color: white; border: 1px solid gray;")
       
        self.reject_btn.clicked.connect(self.emitRejectBtn)
       
        self.approved_btn_2 = QPushButton(self.patient_details_outer_frame)
        self.approved_btn_2.setObjectName(u"approved_btn_2")
        self.approved_btn_2.setGeometry(QRect(360, 780, 181, 41))
        self.approved_btn_2.setFont(font5)
        self.approved_btn_2.setStyleSheet(u"background-color: #E73030; border-radius: 16px; color: white; border: 1px solid gray;")
      
        self.approved_btn_2.clicked.connect(self.emitApprovedBtn)
      
        self.patient_details_label = QLabel(self.background)
        self.patient_details_label.setObjectName(u"patient_details_label")
        self.patient_details_label.setGeometry(QRect(51, 130, 571, 41))
        font6 = QFont()
        font6.setFamily(u"Consolas")
        font6.setPointSize(16)
        self.patient_details_label.setFont(font6)
        self.patient_details_label.setStyleSheet(u"border : none;\n"
"")
        self.doc_availability_label_2 = QLabel(self.background)
        self.doc_availability_label_2.setObjectName(u"doc_availability_label_2")
        self.doc_availability_label_2.setGeometry(QRect(931, 130, 571, 41))
        self.doc_availability_label_2.setFont(font6)
        self.doc_availability_label_2.setStyleSheet(u"border : none;\n"
"")
        self.patient_details_outer_frame_2 = QFrame(self.background)
        self.patient_details_outer_frame_2.setObjectName(u"patient_details_outer_frame_2")
        self.patient_details_outer_frame_2.setGeometry(QRect(920, 180, 751, 841))
        self.patient_details_outer_frame_2.setStyleSheet(u"background-color : #ffffff;")
        self.patient_details_outer_frame_2.setFrameShape(QFrame.StyledPanel)
        self.patient_details_outer_frame_2.setFrameShadow(QFrame.Raised)
        self.clinic_details_inner_2 = QFrame(self.patient_details_outer_frame_2)
        self.clinic_details_inner_2.setObjectName(u"clinic_details_inner_2")
        self.clinic_details_inner_2.setGeometry(QRect(10, 20, 721, 751))
        self.clinic_details_inner_2.setFrameShape(QFrame.StyledPanel)
        self.clinic_details_inner_2.setFrameShadow(QFrame.Raised)
        self.patient_logo_3 = QLabel(self.clinic_details_inner_2)
        self.patient_logo_3.setObjectName(u"patient_logo_3")
        self.patient_logo_3.setGeometry(QRect(9, 9, 54, 54))
        self.patient_logo_3.setFont(font1)
        self.patient_logo_3.setStyleSheet(u"background-color: #B6D0E2; /* Fill color */\n"
"border-radius: 25px; /* Radius to make it round */\n"
"border: 2px solid #B6D0F7; /*  Border color and thickness */\n"
"min-width: 50px; /* Ensure the QLabel is a circle */\n"
"min-height: 50px; /* Ensure the QLabel is a circle */\n"
"max-width: 50px; /* Ensure the QLabel is a circle */\n"
"max-height: 50px; /* Ensure the QLabel is a circle */")
        self.patient_logo_3.setAlignment(Qt.AlignCenter)
        self.doc_name_display_2 = QLabel(self.clinic_details_inner_2)
        self.doc_name_display_2.setObjectName(u"doc_name_display_2")
        self.doc_name_display_2.setGeometry(QRect(9, 69, 120, 22))
        self.doc_name_display_2.setFont(font2)
        self.doc_name_display_2.setStyleSheet(u"border : none;\n"
"")
        self.line_3 = QFrame(self.clinic_details_inner_2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(9, 205, 703, 3))
        self.line_3.setMinimumSize(QSize(357, 3))
        self.line_3.setMaximumSize(QSize(16777215, 3))
        self.line_3.setStyleSheet(u"background-color: #B6D0E2; border: none;")
        self.line_3.setFrameShape(QFrame.StyledPanel)
        self.line_3.setFrameShadow(QFrame.Raised)
        self.time_label_4 = QLabel(self.clinic_details_inner_2)
        self.time_label_4.setObjectName(u"time_label_4")
        self.time_label_4.setGeometry(QRect(10, 220, 221, 148))
        self.time_label_4.setFont(font4)
        self.time_label_4.setStyleSheet(u"border: none;")
        self.time_label_4.setWordWrap(True)
        self.time_available_display_4 = QLabel(self.clinic_details_inner_2)
        self.time_available_display_4.setObjectName(u"time_available_display_4")
        self.time_available_display_4.setGeometry(QRect(260, 220, 451, 148))
        self.time_available_display_4.setMinimumSize(QSize(390, 0))
        self.time_available_display_4.setFont(font3)
        self.time_available_display_4.setStyleSheet(u"border: none;")
        self.time_available_display_4.setScaledContents(False)
        self.time_available_display_4.setWordWrap(True)
        self.date_available_display_5 = QLabel(self.clinic_details_inner_2)
        self.date_available_display_5.setObjectName(u"date_available_display_5")
        self.date_available_display_5.setGeometry(QRect(260, 330, 451, 148))
        self.date_available_display_5.setMinimumSize(QSize(390, 0))
        self.date_available_display_5.setFont(font3)
        self.date_available_display_5.setStyleSheet(u"border: none;")
        self.date_available_display_5.setScaledContents(False)
        self.date_available_display_5.setWordWrap(True)
        self.date_label_5 = QLabel(self.clinic_details_inner_2)
        self.date_label_5.setObjectName(u"date_label_5")
        self.date_label_5.setGeometry(QRect(10, 330, 221, 148))
        self.date_label_5.setFont(font4)
        self.date_label_5.setStyleSheet(u"border: none;")
        self.date_label_5.setWordWrap(True)
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 90, 141, 891))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.layoutWidget_2 = QWidget(self.frame)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(31, 20, 87, 851))
        self.verticalLayout = QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.home_navigation = QToolButton(self.layoutWidget_2)
        self.home_navigation.setObjectName(u"home_navigation")
        self.home_navigation.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_navigation.sizePolicy().hasHeightForWidth())
        self.home_navigation.setSizePolicy(sizePolicy)
        self.home_navigation.setMinimumSize(QSize(85, 96))
        self.home_navigation.setMaximumSize(QSize(85, 96))
        font7 = QFont()
        font7.setFamily(u"Source Sans Pro Semibold")
        font7.setPointSize(10)
        font7.setBold(True)
        font7.setWeight(75)
        self.home_navigation.setFont(font7)
        self.home_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon1 = QIcon()
        icon1.addFile(u"CAD/Images/nav_images/home_page_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.home_navigation.setIcon(icon1)
        self.home_navigation.setIconSize(QSize(70, 70))
        self.home_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.home_navigation.clicked.connect(self.emitHomeBtn)

        self.verticalLayout.addWidget(self.home_navigation)

        self.doctors_navigation = QToolButton(self.layoutWidget_2)
        self.doctors_navigation.setObjectName(u"doctors_navigation")
        self.doctors_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.doctors_navigation.sizePolicy().hasHeightForWidth())
        self.doctors_navigation.setSizePolicy(sizePolicy)
        self.doctors_navigation.setMinimumSize(QSize(85, 96))
        self.doctors_navigation.setMaximumSize(QSize(85, 96))
        self.doctors_navigation.setFont(font7)
        self.doctors_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon2 = QIcon()
        icon2.addFile(u"CAD/Images/nav_images/services_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.doctors_navigation.setIcon(icon2)
        self.doctors_navigation.setIconSize(QSize(70, 70))
        self.doctors_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.doctors_navigation.clicked.connect(self.emitDoctorsBtn)

        self.verticalLayout.addWidget(self.doctors_navigation)

        self.patients_navigation_2 = QToolButton(self.layoutWidget_2)
        self.patients_navigation_2.setObjectName(u"patients_navigation_2")
        self.patients_navigation_2.setEnabled(True)
        sizePolicy.setHeightForWidth(self.patients_navigation_2.sizePolicy().hasHeightForWidth())
        self.patients_navigation_2.setSizePolicy(sizePolicy)
        self.patients_navigation_2.setMinimumSize(QSize(85, 96))
        self.patients_navigation_2.setMaximumSize(QSize(85, 96))
        self.patients_navigation_2.setFont(font7)
        self.patients_navigation_2.setStyleSheet(u"border: none; \n"
"color: white;")
        icon3 = QIcon()
        icon3.addFile(u"CAD/Images/nav_images/feedback_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.patients_navigation_2.setIcon(icon3)
        self.patients_navigation_2.setIconSize(QSize(70, 70))
        self.patients_navigation_2.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.patients_navigation_2.clicked.connect(self.emitPatientsBtn)

        self.verticalLayout.addWidget(self.patients_navigation_2)

        self.settings_navigation = QToolButton(self.layoutWidget_2)
        self.settings_navigation.setObjectName(u"settings_navigation")
        self.settings_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.settings_navigation.sizePolicy().hasHeightForWidth())
        self.settings_navigation.setSizePolicy(sizePolicy)
        self.settings_navigation.setMinimumSize(QSize(85, 96))
        self.settings_navigation.setMaximumSize(QSize(85, 96))
        self.settings_navigation.setFont(font7)
        self.settings_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon4 = QIcon()
        icon4.addFile(u"CAD/Images/nav_images/settings_page_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_navigation.setIcon(icon4)
        self.settings_navigation.setIconSize(QSize(70, 70))
        self.settings_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.settings_navigation.clicked.connect(self.emitSettingsBtn)

        self.verticalLayout.addWidget(self.settings_navigation)

        self.logout_navigation = QToolButton(self.layoutWidget_2)
        self.logout_navigation.setObjectName(u"logout_navigation")
        self.logout_navigation.setEnabled(True)
        sizePolicy.setHeightForWidth(self.logout_navigation.sizePolicy().hasHeightForWidth())
        self.logout_navigation.setSizePolicy(sizePolicy)
        self.logout_navigation.setMinimumSize(QSize(85, 96))
        self.logout_navigation.setMaximumSize(QSize(85, 96))
        self.logout_navigation.setFont(font7)
        self.logout_navigation.setStyleSheet(u"border: none; \n"
"color: white;")
        icon5 = QIcon()
        icon5.addFile(u"CAD/Images/nav_images/logout_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.logout_navigation.setIcon(icon5)
        self.logout_navigation.setIconSize(QSize(70, 70))
        self.logout_navigation.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.logout_navigation.clicked.connect(self.emitLogoutBtn)

        self.verticalLayout.addWidget(self.logout_navigation)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.noti_icon.setText("")
        self.profile_icon.setText("")
        self.profile_btn.setText(QCoreApplication.translate("Form", u"Clinic name", None))
        self.patient_logo_2.setText(QCoreApplication.translate("Form", u"A", None))
        self.patient_name_display.setText(QCoreApplication.translate("Form", u"Patient Name", None))
        self.diagnosis_display.setText(QCoreApplication.translate("Form", u"diagnosis", None))
        self.diagnosis_label_2.setText(QCoreApplication.translate("Form", u"Diagnosis : ", None))
        self.last_checked_by_label.setText(QCoreApplication.translate("Form", u"Last Checked By:", None))
        self.dr_name_display.setText(QCoreApplication.translate("Form", u"Dr name", None))
        self.date_label.setText(QCoreApplication.translate("Form", u"Date:", None))
        self.date_display.setText(QCoreApplication.translate("Form", u"date", None))
        self.time_label_3.setText(QCoreApplication.translate("Form", u"Time:", None))
        self.time_display_3.setText(QCoreApplication.translate("Form", u"Time", None))
        self.doctor_name_display.setText(QCoreApplication.translate("Form", u"Dr name", None))
        self.doctor_prefered_label.setText(QCoreApplication.translate("Form", u"Doctor preferred:", None))
        self.reject_btn.setText(QCoreApplication.translate("Form", u"Reject", None))
        self.approved_btn_2.setText(QCoreApplication.translate("Form", u"Approved", None))
        self.patient_details_label.setText(QCoreApplication.translate("Form", u"Patient Details", None))
        self.doc_availability_label_2.setText(QCoreApplication.translate("Form", u"Doctor Availability", None))
        self.patient_logo_3.setText(QCoreApplication.translate("Form", u"A", None))
        self.doc_name_display_2.setText(QCoreApplication.translate("Form", u"Doctor Name", None))
        self.time_label_4.setText(QCoreApplication.translate("Form", u"Time available:", None))
        self.time_available_display_4.setText(QCoreApplication.translate("Form", u"Time available", None))
        self.date_available_display_5.setText(QCoreApplication.translate("Form", u"Date available", None))
        self.date_label_5.setText(QCoreApplication.translate("Form", u"Date available:", None))
        self.home_navigation.setText(QCoreApplication.translate("Form", u"   Home   ", None))
        self.doctors_navigation.setText(QCoreApplication.translate("Form", u"Doctors", None))
        self.patients_navigation_2.setText(QCoreApplication.translate("Form", u"Patients", None))
        self.settings_navigation.setText(QCoreApplication.translate("Form", u"Settings", None))
        self.logout_navigation.setText(QCoreApplication.translate("Form", u"Logout", None))
    # retranslateUi

    @pyqtSlot()
    def emitHomeBtn(self):
        self.home_navigation_btn_clicked.emit()

    @pyqtSlot()
    def emitDoctorsBtn(self):
        self.doctors_navigation_btn_clicked.emit()

    @pyqtSlot()
    def emitLogoutBtn(self):
        # Emit the custom signal
        self.logout_btn_clicked.emit()
    
    @pyqtSlot()
    def emitSettingsBtn(self):
        # Emit the custom signal
        self.settings_navigation_btn_clicked.emit()

    @pyqtSlot()
    def emitProfileBtn(self):
        # Emit the custom signal
        self.profile_btn_clicked.emit()

    @pyqtSlot()
    def emitPatientsBtn(self):
        self.patients_navigation_btn_clicked.emit()  

    @pyqtSlot()
    def emitApprovedBtn(self):
        # Emit the custom signal
        self.approved_btn_clicked.emit()

    @pyqtSlot()
    def emitRejectBtn(self):
        # Emit the custom signal
        self.reject_btn_clicked.emit()